### PR TITLE
Add flake8 plugins, and I updated existing packages.

### PR DESCRIPTION
**Pull request by ryo-ma**
I added flake8 plugins, and I updated existing packages.
Please make sure following packages.

- flake8-import-order = "*"
- flake8-quotes = "*"
- pep8-naming = "*"
- flake8-print = "*"
- flake8-eradicate = "*"

Let me know if you would like to add other packages.

### CODE REVIEW

**Comment by hide-hayashi** [comment]
Thank you for your adding flake8 plugins.

Check items are increasing, I have one suggestion.
Please add documentation for coding guidelines for developers.
It is OK what items are checked by CI. 
also max-line-length(100), and complexity(10).

**Comment by ryo-ma** [comment]
OK. I will add contribution guideline in docs.

**Comment by ryo-ma** [comment]
I added to docs.
Please check contribution guidelines. @hhayashiool

**Review by hide-hayashi — APPROVED** [review]
Thank you for writing coding guideline.
LGTM

**Comment by YujiAzama** [comment]
lgtm.

**Pull request merged**
