### PR TITLE
Apply mkdocs for document management

### PR DESCRIPTION
**Pull request by YujiAzama**

### CODE REVIEW

**Comment by YujiAzama** [comment]
When executing mkdocs, execute as follows.

```
pip install mkdocs
mkdocs build
mkdocs serve -a 0.0.0.0:8000
```

**Comment by ryo-ma** [comment]
To my mind, you should add mkdocs to Pipfile(dev-part).

**Comment by YujiAzama** [comment]
I added mkdocs package to Pipfile and check command(mkdocs build) to .travis.yml.

**Review by ryo-ma — APPROVED** [review]
LGTM.

**Pull request merged**
